services:
  - type: web
    name: urlhub
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm run render-build
    startCommand: node app.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_URL
        sync: false
